---
title: "SCM"
author: "邱奕勳"
date: "2020/6/7"
output: html_document
---
```{r}
library(Synth)
library(lubridate)
```
#Data-Basque
```{r}
data("basque")
```


```{r}
unique(basque$regionname)
unique(basque$year)
```

```{r}
dataprep.out <- dataprep(foo = basque,
 predictors = c("school.illit", "school.prim", "school.med",
 "school.high", "school.post.high", "invest"),
 predictors.op = "mean", # the operator
 time.predictors.prior = 1964:1969, #the entire time frame from the #beginning to the end
 special.predictors = list(
 list("gdpcap", 1960:1969, "mean"),
 list("sec.agriculture", seq(1961,1969,2),"mean"),
 list("sec.energy",seq(1961,1969,2),"mean"),
 list("sec.industry", seq(1961,1969,2),"mean"),
 list("sec.construction", seq(1961,1969,2),"mean"),
 list("sec.services.venta", seq(1961,1969,2),"mean"),
 list("sec.services.nonventa",seq(1961,1969,2),"mean"),
 list("popdens", 1969, "mean")),
 dependent = "gdpcap", # dv
 unit.variable = "regionno",#identifying unit numbers
 unit.names.variable = "regionname",#identifying unit names
 time.variable = "year",#time-periods
 treatment.identifier = 17,#the treated case
 controls.identifier = c(2:16, 18),#the control cases; all others #except number 17
 time.optimize.ssr = 1960:1969,#the time-period over which to optimize
 time.plot = 1955:1997)#the entire time period before/after the treatment
```

```{r}
dataprep.out$Z1
```

```{r}
synth.out = synth(data.prep.obj = dataprep.out, method = "BFGS")
```
#gdp 差距
```{r}
gaps = dataprep.out$Y1plot - (dataprep.out$Y0plot 
                                     %*% synth.out$solution.w) #控制組乘以權重
```

```{r}
synth.tables = synth.tab(dataprep.res = dataprep.out,
                         synth.res = synth.out)
```

#權重
```{r}
synth.tables$tab.w$w.weights #權重
```

```{r}
synth.tables$tab.pred[1:13,]
```

```{r}
path.plot(synth.res=synth.out,dataprep.res = dataprep.out, 
          Ylab="real per-capita gdp (1986 USD, thousand)",Xlab="year",
          Ylim = c(0,12),Legend = c("Basque country", 
                                    "synthetic Basque country"),
          Legend.position = "bottomright")
```

```{r}
gaps.plot(synth.res = synth.out, dataprep.res = dataprep.out,
 Ylab = "gap in real per-capita GDP (1986 USD, thousand)", Xlab= "year",
 Ylim = c(-1.5,1.5), Main = NA)
```

