---
title: "trash_policy_by_year"
author: "邱奕勳"
date: "2020/6/10"
output: html_document
---
```{r}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext); library(plm);library(readxl);library(Synth);library(reshape2);library(stargazer)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```
#data
##每人每日
```{r}
trash_raw <- read_csv("data/rawtrash.csv", col_types = cols(`一般垃圾 (公噸)` = col_skip(),
`巨大垃圾 (公噸)` = col_skip(),
序號 = col_skip(), `廚餘 (公噸)` = col_skip(),
`總計 (公噸)` = col_skip(), `資源垃圾 (公噸)` = col_skip()))



YearTF <- c()

for (i  in 1:length(trash_raw$統計期)){
  trash_raw$統計期[i] %>% nchar() <=4 -> TF #取年資料
  YearTF %>% append(TF) -> YearTF
}
#data
trash_raw[YearTF,] -> trash_by_year

str_split(trash_by_year$統計期, "年") -> trash_year

for (i in 1:length(trash_year)){
  as.integer(trash_year[[i]][[1]])+1911 -> trash_by_year$統計期[[i]]
}

trash_by_year <-trash_by_year %>% filter(trash_by_year$統計區 %in% c("新北市","臺北市","桃園市","臺中市"     ,"臺南市","高雄市","宜蘭縣","新竹縣","苗栗縣","彰化縣","南投縣","雲林縣","嘉義縣","屏東縣","臺東縣","花蓮縣","澎湖縣","基隆市","新竹市","嘉義市"))

trash_by_year[order(trash_by_year$統計期),] -> trash_by_year

trash_by_year %>% filter(trash_by_year$統計期 <2019) -> trash_by_year
```

##family_consumption 
```{r}
family_consumption <- read_excel("data/平均每戶消費支出.xlsx")

as.numeric(family_consumption$平均每戶消費支出) -> family_consumption$平均每戶消費支出
merge(family_consumption, trash_by_year, all = TRUE) ->merged_trash_by_year #依據統計期統計區merge
```
##disposable_income
```{r}
disposable_income <- read_excel("data/所得收入者各縣市別平均每人可支配所得.xlsx")
as.numeric(disposable_income$平均每人可支配所得) ->disposable_income$平均每人可支配所得
merge(disposable_income, merged_trash_by_year, all = T)->merged_trash_by_year #依據統計期統計區merge
```
##unemployment
```{r}
unemploy <- read_csv("data/unemploy.csv")

#整理colnames
colnames(unemploy) %>% str_split("_") -> a

unemploy_col <- c()
for (i in 1:length(a)){
  unemploy_col %>% append(a[[i]][[1]]) -> unemploy_col
}
colnames(unemploy) <- unemploy_col

#取年資料
YearTF_un <- c()
for (i  in 1:length(unemploy$項目別)){
  unemploy$項目別[[i]] %>%  nchar() < 5 -> TF_un
  YearTF_un %>% append(TF_un) -> YearTF_un
}
unemploy[YearTF_un,] -> unemploy
unemploy %>% filter(unemploy$項目別 %>% as.numeric() >2000 & unemploy$項目別 %>% as.integer() <2019) -> unemploy

for (i in 1:ncol(unemploy)){
  as.numeric(unemploy[[i]]) -> unemploy[[i]]
}

unemploy %>% select("項目別",unique(merged_trash_by_year$統計區)) -> unemploy

#reshape
melt(unemploy, id.vars = "項目別") -> unemploy
colnames(unemploy) <- c("統計期","統計區","失業率")
merge(unemploy, merged_trash_by_year, all = T) ->merged_trash_by_year
```


##numperhousehold
```{r}
num_per_household <- read_excel("data/平均每戶人數.xlsx",
col_types = c("numeric", "text", "numeric"))
num_per_household %>% filter(num_per_household$統計區 %in% unique(merged_trash_by_year$統計區)) -> num_per_household
merge(num_per_household, merged_trash_by_year, all = T) ->merged_trash_by_year #依據統計期統計區merge
```


```{r}
merged_trash_by_year %>% mutate( regionno = as.numeric(factor(merged_trash_by_year$統計區))) -> 
merged_trash_by_year

merged_trash_by_year[order(merged_trash_by_year$regionno),] -> merged_trash_by_year
merged_trash_by_year %>% as.data.frame() -> merged_trash_by_year
```

#SCM
##preparation
```{r}
trashprep.out <- dataprep(
  foo= merged_trash_by_year,
  predictors = c("平均每戶消費支出","失業率","平均每戶人數","平均每人可支配所得","平均每人每日一般廢棄物產生量 (公斤)"),
  predictors.op = "mean",
  time.predictors.prior = 2001:2010,
  dependent = "平均每人每日一般廢棄物產生量 (公斤)",
  unit.variable = "regionno",
  unit.names.variable = "統計區",
  time.variable = "統計期",
  treatment.identifier = 15,
  controls.identifier = c(1:14,16:20),
  time.optimize.ssr = 2001:2010,
  time.plot = 2001:2018
)
```
##minimization
```{r}
synth.out = synth(data.prep.obj = trashprep.out)
```


```{r}
synth.tables = synth.tab(
  dataprep.res = trashprep.out,
  synth.res = synth.out
  )
```
##weights
```{r}
synth.tables$tab.w -> weights_city
weights_city
```
##gaps
```{r}
gaps = trashprep.out$Y1plot - (trashprep.out$Y0plot %*% synth.out$solution.w)
gaps 
```
##gap_sd before treatment
```{r}
gaps[1:10] %>% sd()
```
##characteristics
```{r}
synth.tables$tab.pred -> characterisrics
characterisrics
```


#regression
```{r}
(trashprep.out$Y0plot %*% synth.out$solution.w) -> synthetic_ntp
trashprep.out$Y1plot -> ntp_outcome
cbind( 2001:2018,synthetic_ntp, ntp_outcome) %>% as.data.frame() -> synntp_ntp
colnames(synntp_ntp) <- c("year","synthetic", "新北市")
melt(synntp_ntp, id.vars = "year") -> synntp_ntp #reshape
colnames(synntp_ntp) <- c("統計期","統計區","每人每日")
```

```{r}
synntp_ntp %>% mutate(
   treat = 統計區 == "新北市", 
   post  = 統計期>2010,
   effect = (treat == 1& post == 1)
) ->synntp_ntp


lm(synntp_ntp$每人每日 ~ treat+post+effect, data = synntp_ntp)-> syntheticlm
summary(syntheticlm)
stargazer(syntheticlm, ols_ntp_chang,type = "text")
```



```{r}
ggplot(data=synntp_ntp ,aes(x=synntp_ntp$統計期,y=synntp_ntp$每人每日, 
  color=synntp_ntp$統計區))+
  geom_vline(xintercept = 2010, alpha = 0.7, linetype = "longdash")+
  geom_line()+
  scale_color_manual(values = c("black", "red"))+
  theme(legend.position = "NULL")+
  annotate("text", label = "合成新北市", x= 2016, y= 1.2)+
  annotate("text", label = "新北市", x= 2016, y= 0.8, color = "red")+
  labs(x="統計期(年)", y="平均每人每日一般廢棄物產生量 (公斤)")+
  scale_x_continuous(breaks = c(2001,seq(2005,2015, by=5),2018))->Synntp_ntp_graph
ggsave("Synntp_ntp_graph.png", width = 5, height = 3)
Synntp_ntp_graph

```

